# Generated by Django 4.2.7 on 2025-12-29 16:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _set_inventory_item_owner_forward(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    for item in InventoryItem.objects.select_related('farm'):
        if item.farm_id and item.farm.owner_id:
            item.owner_id = item.farm.owner_id
            item.save(update_fields=['owner'])


def _set_inventory_item_owner_backward(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    InventoryItem.objects.update(owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_set_inventory_item_owner_forward, _set_inventory_item_owner_backward),
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides'), ('equipment', 'Equipment'), ('harvest', 'Harvest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('farm', 'name', 'category')},
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alerted_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-alerted_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='farms.activity')),
                ('related_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='marketplace.listing')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_level',
        ),
    ]
