# Generated by Django 4.2.7 on 2025-12-31 15:29

import django.core.validators
from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models
import django.db.models.deletion
import marketplace.models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_description_inventoryitem_expiry_date_and_more'),
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='unit_price',
            new_name='price_per_unit',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='quantity_available',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='available_to',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('crops', 'Crops'), ('seeds', 'Seeds'), ('equipment', 'Equipment'), ('fertilizers', 'Fertilizers')], default='crops', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(default=marketplace.models._default_expiry),
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listings', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='quality_grade',
            field=models.CharField(choices=[('premium', 'Premium'), ('grade_a', 'Grade A'), ('grade_b', 'Grade B'), ('grade_c', 'Grade C')], default='grade_a', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='PriceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('market', models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail')], default='wholesale', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', max_length=32)),
                ('effective_date', models.DateField(default=timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'unique_together': {('commodity', 'grade', 'market', 'effective_date')},
            },
        ),
    ]
