# Generated by Django 4.2.7 on 2025-12-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_types', models.JSONField(blank=True, default=list)),
                ('irrigation_type', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
