# Generated by Django 4.2.7 on 2025-12-26

from django.conf import settings
import django.contrib.postgres.fields
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='acreage',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='crop_types',
        ),
        migrations.AddField(
            model_name='farm',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='irrigation_type',
            field=models.CharField(
                choices=[
                    ('drip', 'Drip'),
                    ('sprinkler', 'Sprinkler'),
                    ('flood', 'Flood'),
                    ('none', 'None'),
                ],
                default='none',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(
                choices=[
                    ('loam', 'Loam'),
                    ('clay', 'Clay'),
                    ('sandy', 'Sandy'),
                    ('silt', 'Silt'),
                    ('peat', 'Peat'),
                ],
                default='loam',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_number', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(0)])),
                ('current_crop', models.CharField(blank=True, max_length=255)),
                ('crop_history', models.JSONField(blank=True, default=list)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[MinValueValidator(0), MaxValueValidator(14)])),
                ('last_fertilized_date', models.DateField(blank=True, null=True)),
                ('last_harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
            options={
                'ordering': ['field_name'],
                'unique_together': {('farm', 'field_number')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('planting', 'Planting'), ('fertilizing', 'Fertilizing'), ('irrigation', 'Irrigation'), ('pest_control', 'Pest Control'), ('weeding', 'Weeding'), ('harvesting', 'Harvesting')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[MinValueValidator(0)])),
                ('weather_conditions', models.JSONField(blank=True, default=dict)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.field')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
