# Generated by Django 4.2.7 on 2025-12-29 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0003_farm_management_system'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farm',
            unique_together={('owner', 'name')},
        ),
    ]
